sf4ldap:
  command: [--copy-service]
  image: osixia/openldap:1.3.0
  volumes:
    - ./docker/ldap/sf4app.schema:/container/service/slapd/assets/config/bootstrap/schema/sf4app.schema
    - ./docker/ldap/people.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/people.ldif
  ports:
    - "389:389"
    - "636:636"
  expose:
    - 389
    - 636
  environment:
    - LDAP_ADMIN_PASSWORD=myadminpasswd
    - LDAP_DOMAIN=sf4app.org